### ISSUE TITLE
What files should be in the gt_path folder?

### ISSUE THREAD

**Issue by JeonghanSeock** [eragonruan/text-detection-ctpn#18]
Hello. eragonruan !
I was very surprised to see your code.
Thank you for sharing a good source.
I want to train my own image data.
You told me to edit the file split_label.py ("path" and "gt_path").
I think there is an image in the "path" folder.
But, I don't know about "gt_path".

What files should be in the "gt_path" folder? and
Can you give me some sample? (one image and gt_path.txt)

Thanks you!

**Comment by eragonruan** [comment]
@JeonghanSeock For example. one imgge named img_1.png with on gt file named gt_img_1.txt
in gt_img_1.txt, each text instance are labelled in x1,y1,x2,y2,x3,y3,x4,y4. Since this repo is used to detect horizontal text, if you have gt labelled in x,y,w,h is ok, just write a script to transform it to previous format. you can check this [link](http://rrc.cvc.uab.es/?ch=8&com=tasks), I used this dataset(multi-lingual scene text dataset) to train the model. you can find more about the data in this page.

**Comment by JeonghanSeock** [comment]
Thank you so much eragonruan!!
Hava a good day!

**Comment by ericosmic** [comment]
@Jeonghan-Seok   Could you tell how to prepare the gt data,  is any programm fro batch handle.
