### ISSUE TITLE
What is the format of gt file?

### ISSUE THREAD

**Issue by ZhengWei0918** [eragonruan/text-detection-ctpn#34]
I read the code in split_label.py and found the label information for each image is in gt file in gt_path, but I do not know the format you are using in this file. Can you kindly share the format of that? Thx.

**Comment by eragonruan** [comment]
@ZhengWei0918 each text instance is labelled in x1,y1,x2,y2,x3,y3,x4,y4. Since this repo is used to detect horizontal text, if you have gt labelled in x,y,w,h is ok, just write a script to transform it to previous format. you can check this [link](http://rrc.cvc.uab.es/?ch=8&com=tasks), I used this dataset(multi-lingual scene text dataset) to train the model. you can find more about the data in this page.

**Comment by eragonruan** [comment]
close for now
