### ISSUE TITLE
i am getting can not import name 'model_train'

### ISSUE THREAD

**Issue by aztbzkrt** [eragonruan/text-detection-ctpn#377]
```
C:\Users\Dell\Desktop\text-detection-ctpn-banjin-dev\main>demo.py
Traceback (most recent call last):
  File "C:\Users\Dell\Desktop\text-detection-ctpn-banjin-dev\main\demo.py", line 13, in <module>
    from nets import model_train as model
ImportError: cannot import name 'model_train'
```

**Comment by MassonAntoine** [comment]
Hello @aztbzkrt, I try to run the demo and having the same error as you. Could you tell me how you solved it ?

**Comment by sinny777** [comment]
Im also getting the same error..

**Comment by Hito-toro** [comment]
@sinny777 I resolved this error, just play a bit with file location and you could be able to solve this. I'm sorry, I'm not able to provide you a more precise answer x')

**Comment by jasoriya** [comment]
So after facing the same error, I figured out what was being done wrong. The problem is due to the fact that you are running `demo.py` from the `main` folder. Python tries to find model_train.py in the tensorflow/models/research/slim PATH. 

There is a folder named `nets` in text-detection-ctpn folder which contains model_train.py. So the correct way of running the program is from text-detection-ctpn folder as stated in the Readme.

Just run -> python ./main/demo.py

**Comment by sandeep-zeni** [comment]
Solved it by adding "__init__.py" in nets folder.

**Comment by ebinzacharias** [comment]
Add `__init__.py` file in the folder that contains the module to import. 
So in this case, add this empty file to /nets.

### Now run python3 ./main/demo.py from the root folder. 

#### If you want to run the demo.py from the main folder, change the paths inside demo.py.
