### ISSUE TITLE
hello, i find ctpn has some trouble with small words!!!

### ISSUE THREAD

**Issue by cjt222** [eragonruan/text-detection-ctpn#48]
hello,  i find ctpn has some trouble with small words!!just like image below.i have 1500 images and maybe 100 images which contain small words.i finetune model which you provide and set batch size 512 and after 2000iters,total loss is 0.5.
![00012_00167](https://user-images.githubusercontent.com/17508662/33118781-d538d69c-cfa7-11e7-8c7c-16112a2d1d9f.jpg)

i try to resize image to 1000x2000 as split_label.py and input t o network, but it can not detect image  correctly,in image, size of each words maybe 20x20 pixels

**Comment by eragonruan** [comment]
@cjt222 Several details may related to your problem. First, the smallest anchor height is 11. Second, some hyper parameter about text connector, you can draw the proposals rather than text lines to see whether the network is working properly. If proposals seems right, multi-scale test and modify text connector parameter may be of help.

**Comment by fendaq** [comment]
@cjt222 hello ,i meet the same trouble, do you find  any solution? thx
