### ISSUE TITLE
Why undefine roi_pool_op and psroi_pooling_op?

### ISSUE THREAD

**Issue by cclauss** [eragonruan/text-detection-ctpn#5]
These two imports are commented out.
* [roi_pool_op](https://github.com/eragonruan/text-detection-ctpn/blob/master/lib/networks/network.py#L6) is required on [line 211](https://github.com/eragonruan/text-detection-ctpn/blob/master/lib/networks/network.py#L211).
* [psroi_pooling_op](https://github.com/eragonruan/text-detection-ctpn/blob/master/lib/networks/network.py#L11) is required on [line 227](https://github.com/eragonruan/text-detection-ctpn/blob/master/lib/networks/network.py#L227).

**Comment by eragonruan** [comment]
@cclauss network.py is a commomly used class to build network. ROI pooling is used in faster rcnn, but in ctpn, we do not need roi pooling since the output dimension of the RNN layer is same. For more detail. you can refer to the paper or my [blog](http://slade-ruan.me/2017/10/22/text-detection-ctpn/)
